language: rust
sudo: 9000
dist: trusty
rust:
  - nightly

branches:
  except:
    - master
notifications:
  webhooks: http://build.servo.org:54856/travis
script:
  - travis_wait cargo build --verbose
  - travis_wait cargo test --verbose
